{
    'name': 'Smart Radar',
    'version': '1.0',
    'category': 'Administration',
    'summary': 'AI SaaS Platform Management & Dashboard',
    'description': """
    Smart Radar - Zero-Touch AI SaaS Platform.
    Manage API keys and view real-time SaaS operations in a bespoke OWL Dashboard.
    """,
    'author': 'Alpha Plus IT',
    'depends': ['base', 'web'],
    'data': [
        'security/ir.model.access.csv',
        'data/demo_data.xml',
        'views/target_views.xml',
        'views/post_views.xml',
        'views/client_config_views.xml',
        'views/res_config_settings_views.xml',
        'views/menu.xml',
    ],
    'assets': {
        'web.assets_backend': [
            'smart_radar/static/src/core/scss/_variables.scss',
            'smart_radar/static/src/core/scss/_animations.scss',
            'smart_radar/static/src/core/scss/design_system.scss',
            'smart_radar/static/src/scss/backend_views.scss',
            'smart_radar/static/src/components/dashboard/dashboard.scss',
            'smart_radar/static/src/components/posts/posts_page.scss',
            'smart_radar/static/src/components/targets/targets_page.scss',
            'smart_radar/static/src/components/config/config_page.scss',
            'smart_radar/static/src/services/radar_service.js',
            'smart_radar/static/src/components/dashboard/**/*.js',
            'smart_radar/static/src/components/dashboard/**/*.xml',
            'smart_radar/static/src/components/posts/**/*.js',
            'smart_radar/static/src/components/posts/**/*.xml',
            'smart_radar/static/src/components/targets/**/*.js',
            'smart_radar/static/src/components/targets/**/*.xml',
            'smart_radar/static/src/components/config/**/*.js',
            'smart_radar/static/src/components/config/**/*.xml',
        ],
    },
    'installable': True,
    'application': True,
    'license': 'OPL-1',
}
